#!/bin/bash

mkdir ${ADTTMP}/locale
localedef -c -i en_US -f UTF-8 ${ADTTMP}/locale/en_US.utf8

dh_auto_configure -- \
    -Dunicode_support=icu \
    -Dfts=true \
    -Dstemmer=enabled \
    -Dfunctional_tests=true \
    -Dnetwork_manager=disabled \
    -Dsystemd_user_services=/usr/lib/systemd/user \
    --libexecdir=/usr/lib/tracker

LOCPATH=${ADTTMP}/locale \
    HOME=${ADTTMP} \
    LANG=en_US.utf8 \
    LC_ALL=en_US.utf8 \
    dbus-run-session -- dh_auto_test 2> >(grep -vE '^(Activating|Successfully activated)')>&2
