
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */


#ifndef __TRACKER_DATA_ENUM_TYPES_H__
#define __TRACKER_DATA_ENUM_TYPES_H__

#include <glib-object.h>
#include "tracker-db-interface-sqlite.h"

G_BEGIN_DECLS

/* enumerations from "tracker-db-interface-sqlite.h" */
GType tracker_db_interface_flags_get_type (void) G_GNUC_CONST;
#define TRACKER_TYPE_DB_INTERFACE_FLAGS (tracker_db_interface_flags_get_type ())
G_END_DECLS

#endif /* __TRACKER_ENUMS_TYPES_H__ */

/* Generated data ends here */

